### ISSUE TITLE
How to scroll the page when side bar is opened ?

### ISSUE THREAD

**Issue by vinylroads** [simple-sidebar/simpler-sidebar#16]
Hello,

When side bar is opened, we can’t scroll the page. Is it possible to activate the scroll ?

Regards,

Sébastien

**Comment by dcdeiv** [comment]
As in apps, you can't scroll the page while the sidenav is opened.
But in feature releases I can add an option to do that

**Comment by vinylroads** [comment]
Hi,

I understand.

something like this would be nice :

`$.fn.simplerSidebar.settings.scroll = true;`

**Comment by dcdeiv** [comment]
Thanks for this advice, I will implement it asap

**Comment by dcdeiv** [comment]
That is now possible by adding this option:
`events.callbacks.animation.freezePage: false`.
Remember to hide the mask too: `mask.display: false`

Before updating your local simpler-sidebar package, be sure to read the [changelog](https://github.com/simple-sidebar/simpler-sidebar/doc/changelogs/v2.0.0.md). **Upgrading without migrating will broke your scripts**.

**Comment by vinylroads** [comment]
Hi,

Thank you for this update !

What do you mean by "Upgrading without migrating" ?

I thought i had only to replace with new plugin files and update js.

Regards,

/Sébastien

**Comment by dcdeiv** [comment]
Optional have changed, so basically of you update the js file, your web page will broke! V1.* And v2.* Are not compatible due to a new options list! In the readme and in the doc folder everything is explained!

**Comment by vinylroads** [comment]
Hi,

Thank you to have updated the plugin. Works like a charm. We can now scroll website when sidebar is opened.

See it in action : http://www.agencemagnum.com

**Comment by dcdeiv** [comment]
Awesome!
