### ISSUE TITLE
event-driven callback

### ISSUE THREAD

**Issue by ericandrewscott** [simple-sidebar/simpler-sidebar#21]
Do you have any hooks for events that can fire when the sidebar is open or closed? Something like Bootstrap's modal:

```javascript
$('#myModal').on('shown.bs.modal', function () {
  // do some stuff
})
```

If not, I'll see if I can extend it and open a PR. Thanks in advance!

**Comment by dcdeiv** [comment]
There isn't such a gestire yet and I think that by now I am not able to add it! When I  will manage to do it, I will certainly add it! Some help would be great!

**Comment by ericandrewscott** [comment]
Updated the main JS file and ran it through your linter via grunt.... here's the PR:
https://github.com/dcdeiv/simpler-sidebar/pull/22

Now you could run some extra JS in an application by using something like:
```javascript
        $('body').on('open.panel', function (e) {
            // do some stuff
        });
```
or:
```javascript
        $('body').on('close.panel', function (e) {
            // do some stuff
        });
```

**Comment by dcdeiv** [comment]
The code would be changed to be a fully functional plugin. In this way the event driven callbacks will be available for all instances instead of being able for the instance of the object.
I will add this functionality soon. I'm already working on it, but in the jquery plugin way:

```js
$sidebar.simpler-sidebar( {
  // Other Options
  callbacks: {
    onClose: function() {},
    onOpen: function() {}
  }
} );
```

**Comment by ericandrewscott** [comment]
@dcdeiv that works for me. I only have one instance of the sidebar in my application, but ideally, you're right!

**Comment by ericandrewscott** [comment]
:+1:

**Comment by dcdeiv** [comment]
This is now possible in [v2.0.0](https://github.com/simple-sidebar/simpler-sidebar/releases/tag/v2.0.0).
Quoting the [changelog](https://github.com/simple-sidebar/simpler-sidebar/doc/changelogs/v2.0.0.md):

## 3 - Add the ability to set custom functions to run when/after all the animations are triggered. [#21](https://github.com/simple-sidebar/simpler-sidebar/issues/21)
That is preatty easy, and you can test them in the [demo](https://github.com/simple-sidebar/simpler-sidebar/demo) folder.

In the options there is a brand new feature: `events`. This wrapper will handle all your functions according to some events that occur in the plugin. By now I have added only the `animation` event.

You can add some custom functions to be triggered when/after the animations.

- `events.on.animation` will handle all your custom functions that must be run when the animation is triggered.
- `events.callbacks.animation` will handle all your custom functions that must be run after the animation has been triggered.
- `open` in the animation that opens the sidebar.
- `close` is the animation that closes the sidebar.
- `both` will run your custom functions on both animations.

```javascript
var callopen = function() {
      alert( "callback called after the sidebar's been opened" );
    },
    callclose = function() {
      alert( "callback called after the sidebar's been closed" );
    },
    callboth = function() {
      alert( "callback called after both animations" );
    },
    onopen = function() {
      alert( "function called while the sidebar is opening" );
    },
    onclose = function() {
      alert( "function called while the sidebar is closing" );
    },
    onboth = function() {
      alert( "function called while both animations are triggered" );
    };

$( "#sidebar" ).sidebarBones( {
  // Required options are in this example skipped.
  events: {
    on: {
      animation: {
        open: onopen,
        close: onclose,
        both: onboth
      }
    },
    callbacks: {
      animation: {
        open: callopen,
        close: callclose,
        both: callboth,
        freezePage: true
      }
    }
  },
} );
```
