### ISSUE TITLE
Please, help up upgrade the plugin!

### ISSUE THREAD

**Issue by daslicht** [simple-sidebar/simpler-sidebar#25]
Hi,
is there a way to keep the scrollbar , please?
At the moment the content will jump anytime the Sidebar is opened and closed.

After inspecting the code I found : ```freezePage```

Is there a way to set this to ```false``` ?

Best Regards
Marc

**Comment by dcdeiv** [comment]
Do you mean [this](https://github.com/simple-sidebar/simpler-sidebar/blob/master/doc/OPTIONS.md#eventscallbacksanimationfreezepage) option?

Have you checked out the demo pages? Especially [this](https://github.com/simple-sidebar/simpler-sidebar/blob/master/demo/right-left.html) one?

Have you properly [migrated](https://github.com/simple-sidebar/simpler-sidebar/blob/master/doc/changelogs/v2.0.2.md) to the [latest](https://github.com/simple-sidebar/simpler-sidebar/releases/tag/v2.0.2) version?

Can you post your snippet code?

**Comment by dcdeiv** [comment]
```javascript
events: {
        callbacks: {
            animation: {
                freezePage: false
            }
        }
    }
```

**Comment by daslicht** [comment]
Hi, thank you for you reply !

here is the sidebar in action : 

http://goo.gl/k6XJsM


I have just tried to add that freesPage option but it do not seam to have an effect.



```
  var closingLinks = '.close-sidebar';
   $('#sidebar').show();
    var $sidebar = $('#sidebar').simplerSidebar({
    	opener: '.navbar-toggler',
    	animation: {
    		duration: 500,
    		easing: 'easeOutQuint'
    	},
    	sidebar: {
    		align: 'left',
    		width: 250,
    		closingLinks: closingLinks,
    	},
    	mask: {
    		display: true
    	},
		events: {
        callbacks: {
            animation: {
                freezePage: false
            }
        }
    }

    });
```

**Comment by daslicht** [comment]
Just tried upgrading to the latest version but with the same code which worked before I get : 
```
Uncaught TypeError: Cannot read property 'trigger' of undefined
```

**Comment by dcdeiv** [comment]
Do you use Bower, npm or did you just download the code from Github?

1. YOU HAVE TO UPDATE YOUR LOCAL PACKAGE TO V2.0.2
  - v1.x.x *is not compatible* with v2.x.x. Read the [Semantic Versioning wiki](http://semver.org/) to know more about it. That is stated also [right here](https://github.com/simple-sidebar/simpler-sidebar#latest-release)!
  - OPTIONS HAVE CHANGED! Did you read the [changelog](https://github.com/simple-sidebar/simpler-sidebar/tree/master/doc/changelogs)? YOU HAVE TO MIGRATE TO V2.0.2!!
  - DID YOU READ THE [OPTIONS DOCUMENTATION](https://github.com/simple-sidebar/simpler-sidebar/blob/master/doc/OPTIONS.md)?
2. Have you followed the [getting started guidelines](https://github.com/simple-sidebar/simpler-sidebar#getting-started)?
3. Your code is old and full of mistakes!!!
  - Please update the package and your custom options to v2.0.2!!! THAT MEANS THAT YOU HAVE TO UPDATE THE OPTIONS TOO!!!!!!!!!

```javascript
var $sidebar = $( "#sidebar" );

$sidebar
	.show()
	.simplerSidebar( {
		align: "left", // the new sidear.align
		selectors: {
			trigger: ".navbar-toggler", // the new opener
			quitter: ".close-sidebar" // the new closingLinks
		},
		animation: {

			//duration: 500, // that is default, you can remove this line
			easing: "easeOutQuint"
		},
		sidebar: {
			width: 250
		},
		/*
		** This is default, you can remove this option!
		mask: {
			display: true
		},
		*/
		events: {
			callbacks: {
				animation: {
					freezePage: false
				}
			}
		}
	} );
```

**Comment by dcdeiv** [comment]
Duplicate of #16

**Comment by dcdeiv** [comment]
If you need some help, please ask.
But be sure to read all documentation before asking!

**Comment by daslicht** [comment]
`Please, help up upgrade the plugin!`
pardon ?

`YOU HAVE TO UPDATE YOUR LOCAL PACKAGE TO V2.0.2`
yes I tried via bower and the [zip] (https://github.com/simple-sidebar/simpler-sidebar/releases/tag/v2.0.2)

`Have you followed the getting started guidelines?`
yes

```
Your code is old and full of mistakes!!!
Please update the package and your custom options to v2.0.2!!! THAT MEANS THAT YOU HAVE TO UPDATE THE OPTIONS TOO!!!!!!!!!
```
keep cool

Have a nice day!

**Comment by dcdeiv** [comment]
What I am trying to say is that you ugraded the package but not your options.

When packages have to be upgrade from v1.x.x to v2.x.x this means that the new version is a major release, thus the two options and packages won't live nice together.

**Everything is changed**. That is why the package isn't working, you are using the old options api. That means that you have to upgrade them.

I also rewrote your options upgrading them to the new features and options in v2.0.2 before:
```javascript
var $sidebar = $( "#sidebar" );

$sidebar
    .show()
    .simplerSidebar( {
        align: "left", // the new sidear.align
        selectors: {
            trigger: ".navbar-toggler", // the new opener
            quitter: ".close-sidebar" // the new closingLinks
        },
        animation: {

            //duration: 500, // that is default, you can remove this line
            easing: "easeOutQuint"
        },
        sidebar: {
            width: 250
        },
        /*
        ** This is default, you can remove this option!
        mask: {
            display: true
        },
        */
        events: {
            callbacks: {
                animation: {
                    freezePage: false
                }
            }
        }
    } );
```

I have provided a [brand new getting started guide](https://github.com/simple-sidebar/simpler-sidebar/#simpler-sidebar) along with the v2.0.2, a [brand new doc folder](https://github.com/simple-sidebar/simpler-sidebar/tree/master/doc) with all explanation of the [new options](https://github.com/simple-sidebar/simpler-sidebar/blob/master/doc/OPTIONS.md) and a [changelog too](https://github.com/simple-sidebar/simpler-sidebar/blob/master/doc/changelogs/v2.0.2.md) with a [migrate section](https://github.com/simple-sidebar/simpler-sidebar/blob/master/doc/changelogs/v2.0.2.md#migrate-plugin-options) that helps to bring old features to the new ones. And you are just ignoring them!

I also gave you the links in the previous posts and you didn't read them.

I am angry because I am telling you this *several times*, but you just keep _ignoring_ what I am saying.

**Comment by daslicht** [comment]
Anything is fine :)
you know... , these messages are not in real time.
I have immediately inspected you links and upgraded to version 2.0.2 as well as the code you kindly provided for me. But it didn't worked, yet.

I cant test it further right now, since out webserver is  doing some updates at the moment and not responding :/

If you like I keep you posted.

Thank you very much for your time !

**Comment by dcdeiv** [comment]
Yes, please! Keep me updated! But please, do not edit previous post, because I can't be notified of that changes!

**Comment by daslicht** [comment]
Yeah editing posts seam to be less good and lead to misunderstandings :)

**Comment by dcdeiv** [comment]
As soon as your server will be online I will inspect the source code. Maybe there are some issues with other packages or plugins. In the mean time, check all [new demo pages](https://github.com/simple-sidebar/simpler-sidebar/tree/master/demo)!

**Comment by daslicht** [comment]
The Server is back. 
Looks like the sidebar gets initialized but the trigger have no effect.
Here is the code I am using : 
http://goo.gl/GEAoEf

**Comment by dcdeiv** [comment]
I need to see the source code of the sentire HTML page! Right now I don't have a PC to inspect it, I will answer you as soon as I get to a PC.

By now try to remove the show method and all comments!
Also check if the selectors are right!

**Comment by daslicht** [comment]
`I need to see the source code of the sentire HTML page! `
Here ya go : 
```
<button class="navbar-toggler hidden-md-up" type="button">
    &#9776;
</button>
<!-- http://dcdeiv.github.io/simpler-sidebar/ -->
<div id="sidebar" class=''>
    <div id="sidebar-wrapper" class="sidebar-wrapper bg-primary z-depth-1">
        <a href="/" title="home" class="sidebar-brand p-a-1">
            <img class="img-fluid" src="{{'/assets/images/logo/image.jpg' | theme}}" alt="JumpLink Logo">
        </a>

         <!--<a href="/" class="navbar-brand">&nbsp;</a>-->
        <div class="list-group">
            <a href="{% if this.page.id != 'home' %}{{'home'|page}}{% endif %}/shipping" class="close-sidebar list-group-item">Shipping</a></li>
            <a href="{% if this.page.id != 'home' %}{{'home'|page}}{% endif %}liner-services" class="close-sidebar list-group-item">Liner Services</a></li>
            <a href="{% if this.page.id != 'home' %}{{'home'|page}}{% endif %}port-agency" class="close-sidebar list-group-item">Port Agency</a>
            <a href="{% if this.page.id != 'home' %}{{'home'|page}}{% endif %}offshore" class="close-sidebar list-group-item">Offshore</a>
            <a href="{% if this.page.id != 'home' %}{{'home'|page}}{% endif %}contact" class="close-sidebar list-group-item">Contact</a>          
        </div>
    </div>
</div>
```
`By now try to remove the show method and all comments!
`
That was the first i tried :)


`Also check if the selectors are right!`
of course 8)

**Comment by dcdeiv** [comment]
Are the changes online at the previous link you provided to me? I managed to inspect the source code with my mobile at [this link](view-source:breb.jumplink.eu). I can't see at the bottom of the page the jquery and jquery-ui CDN s nor the sidebar options code!

**Comment by dcdeiv** [comment]
OK I find out the sonar code at [this link]http://breb.jumplink.eu/themes/breb/assets/javascript/pages/navigation.js).
Where is jquery?

**Comment by daslicht** [comment]
The  sidebar is initialized here:
http://goo.gl/GEAoEf

See the console, ```console.log('navigation.js called');``` 
that verifies that the file is running and jquery present.
Besides that version 1.4 was working except the freeze option

**Comment by daslicht** [comment]
please do not post the link public which contains client names .

**Comment by dcdeiv** [comment]
OK, I'll answer you later when I get to my PC. I removed the links!

**Comment by daslicht** [comment]
the following assets are combined : 
```
<script src="{{ [
    'assets/vendor/jquery/dist/jquery.min.js',
    'assets/vendor/jquery-ui/jquery-ui.min.js',
    'assets/vendor/tether/dist/js/tether.js',
    'assets/vendor/bootstrap/dist/js/bootstrap.js',
    'assets/vendor/slick-carousel/slick/slick.js',
    'assets/vendor/masonry/dist/masonry.pkgd.min.js',
    'assets/vendor/simpler-sidebar/dist/jquery.simpler-sidebar.min.js'
]|theme }}"></script>
```

output:
goo.gl/zKhb01

yeah take you time !

**Comment by dcdeiv** [comment]
OK, so everything is included but I still can't find out why the sidebar
isn't responding. Demos works fine, so I fear there are incompatibility
issues with other plugins!

Il 01 ago 2016 16:11, "Marc Wensauer" <notifications@github.com> ha scritto:

**Comment by daslicht** [comment]
I try to narrow it down

**Comment by dcdeiv** [comment]
I finally had time to inspect your code carefully and in the file where you combine the vendor libs, the simpler-sidebar plugin is not updated.

As you can see, this is the header I've found at the bottom of the page:

```javascript
/*! simpler-sidebar v1.4.11 (https://github.com/dcdeiv/simpler-sidebar#readme)
** Copyright (c) 2015 - 2016 Davide Di Criscito
** Dual licensed under MIT and GPL-2.0
*/
```

The current header is:
```javascript
/*! simpler-sidebar v2.0.2 (https://github.com/simple-sidebar/simpler-sidebar#readme)
** Copyright (c) 2015 - 2016 Davide Di Criscito
** Dual licensed under MIT and GPL-2.0
*/
```

The **simpler-sidebar** plugin has been moved from https://github.com/dcdeiv/simpler-sidebar to https://github.com/simple-sidebar/simpler-sidebar. If you are using Bower there should not be any problems because I manually changed the bower repository to link to the new git repository.

However, if you are using a task runner such as Grunt or Gulp, you should run the combine command again to fetch the latest updates!

**Comment by daslicht** [comment]
Application Cache cleared and anything is working !

Thank you very much !
