### ISSUE TITLE
'Readme - Getting Started' needs revision; I followed it and get a blank page.

### ISSUE THREAD

**Issue by joe-oli** [simple-sidebar/simpler-sidebar#32]
- [x ] I have installed the [latest](https://github.com/simple-sidebar/simpler-sidebar/releases/latest) version
  - [x ] I have downloaded the plugin with `github`

## Actual behavior
Blank page

## Steps to reproduce the behavior
Follow the instructions on the Getting Started readme.

I ended up with the following HTML, which gives me a blank page !
(attached - renamed html extension to txt for github to accept )

[sidebarNav.html.txt](https://github.com/simple-sidebar/simpler-sidebar/files/1092878/sidebarNav.html.txt)

## Expected behavior
Basic page showing sidenav

**Comment by dcdeiv** [comment]
Please, provide a full html page example

**Comment by joe-oli** [comment]
provided, edited my original post to include attachement (instead of inline html which github reformatted)

**Comment by dcdeiv** [comment]
Please, check this link

<script src="./simpler-sidebar-master/dist/jquery.simpler-sidebar.min.js"></script>

Demos are also provided. Try check them out.

**Comment by joe-oli** [comment]
Nothing wrong with my link. I have downloaded the zip from github, the file is being found and loaded, no errors in Chrome console.

**Comment by dcdeiv** [comment]
Try adding some text, some more style, maybe a real button. The readme is not meant to work right away. Comments says that the button can be whatever you want. Now it's nothing. Page is white so you don't see anything. Navebar is white, the sidebar is hidden and there's no button to trigger it. Try read more carefully and use the demos too.
