### ISSUE TITLE
animate and easing bugs?

### ISSUE THREAD

**Issue by laynetrain** [simple-sidebar/simpler-sidebar#34]
- [X] I have carefully read the [README.md](https://github.com/simple-sidebar/simpler-sidebar/blob/master/README.md) file
- [X] I have installed the [latest](https://github.com/simple-sidebar/simpler-sidebar/releases/latest) version
  - [X] I have downloaded the plugin with `github`
  - [ ] I have downloaded the plugin with `npm` - `npm install simpler-sidebar`
  - [ ] I have downloaded the plugin with `bower` - `bower install simpler-sidebar`
    - [ ] I have checked if the version mentioned in the copyright header of the `dist/jquery.simpler-sidebar.js` file is the same as the [latest](https://github.com/simple-sidebar/simpler-sidebar/releases/latest) version
      - [ ] The plugin won't update
        - [ ] I have run `bower install simpler-sidebar -F` to force latest version on conflict
        - [ ] I have tried to uninstall the package, cleared the cache, and reinstalled it but the version mentioned in the copyright header is the same as the [latest](https://github.com/simple-sidebar/simpler-sidebar/releases/latest) version
- [ ] I have migrated from **v1.x.x** to **v2.x.x**
  - [X] I have carefully read the [RELEASES.md](https://github.com/simple-sidebar/simpler-sidebar/blob/master/doc/RELEASES.md) file in the `doc` folder
  - [X] I have carefully read the *latest changelog* file in the [doc/changelog](https://github.com/simple-sidebar/simpler-sidebar/tree/master/doc/changelogs) folder
  - [X] I have carefully read the [OPTIONS.md](https://github.com/simple-sidebar/simpler-sidebar/blob/master/doc/OPTIONS.md) file in the `doc` folder
  - [ ] I don't understand how to migrate
- [ ] I have found a bug
  - [ ] I am using jQuery v1.x.x
  - [X] I am using jQuery v2.x.x
  - [X] I am using jQuery v3.x.x
- [ ] I want to suggest a new feature
  - [ ] I have carefully read the [CONTRIBUTING.md](https://github.com/simple-sidebar/simpler-sidebar/blob/master/CONTRIBUTING.md) file
  - [X] I have followed the coding style conventions I saw in files
    - [ ] I have used the `editorconfig` plugin in my editor
    - [ ] I have used the `jscs` plugin in my editor
    - [ ] I have used the `jshint` plugin in my editor
  - [ ] I have run `grunt lint` to test if I made some mistakes
  - [ ] I have run `grunt build` to apply changes
  - [X] I have tested the plugin by using the `demo` folder on my computer

## Actual behavior
When I click on the object that I expect to trigger the sidebar to open, I get the following error in the js console:

// if i try jquery 3.1.0
//
jquery.simpler-sidebar.js:213 Uncaught TypeError: $sidebar.animate is not a function
    at animateOpen (VM2272 jquery.simpler-sidebar.js:213)
    at HTMLAnchorElement.<anonymous> (VM2272 jquery.simpler-sidebar.js:288)
    at HTMLAnchorElement.dispatch (VM2265 jquery-3.2.1.slim.min.js:3)
    at HTMLAnchorElement.q.handle (VM2265 jquery-3.2.1.slim.min.js:3)
animateOpen @ jquery.simpler-sidebar.js:213
(anonymous) @ jquery.simpler-sidebar.js:288
dispatch  @ jquery-3.2.1.slim.min.js:3
q.handle  @ jquery-3.2.1.slim.min.js:3

// if i try jquery 3.2.1 and 2.2.4
//
jquery.min.js:3 Uncaught TypeError: r.easing[this.easing] is not a function
    at init.run (VM2587 jquery.min.js:3)
    at i (VM2587 jquery.min.js:3)
    at Function.r.fx.timer (VM2587 jquery.min.js:3)
    at gb (VM2587 jquery.min.js:3)
    at HTMLDivElement.g (VM2587 jquery.min.js:3)
    at Function.dequeue (VM2587 jquery.min.js:3)
    at HTMLDivElement.<anonymous> (VM2587 jquery.min.js:3)
    at Function.each (VM2587 jquery.min.js:2)
    at r.fn.init.each (VM2587 jquery.min.js:2)
    at r.fn.init.queue (VM2587 jquery.min.js:3)

## Steps to reproduce the behavior
* Download the latest from git
* Add jquery in <script> at the bottom of the page
* Add jquery.simpler-sidebar.js <script> after that
* Add allow-scrolling.js <script> after that
* Paste in the html from the demo, except swap out the hamburger icon for the link below
* Paste in the css from the demo (added a high z-index just to be sure)
* Clear cache
* Click on this: `<a href="#" id="sidebar-main-trigger" class=".toggle-sidebar">test</a>`

## Expected behavior
I expect to click the # link above and have the sidebar appear

**Comment by laynetrain** [comment]
Thank you for any help! =)

**Comment by dcdeiv** [comment]
Did you use the demo page as example? I've just tested it and it works as expected!
Have you included jquery, jquery-ui and the simpler-sidebar script before the allow-scrolling.js script?
Link above is not working!
I need to see exactly how your html and js pages are made and where they are put in your website to help you!

**Comment by laynetrain** [comment]
Ah, the readme file made it seem like jqueryui was optional. It is working now using jquery 3.1.0 and jqueryui 1.12.1. 

Although, now the sidebar does not want to stay open on the page. As you can see here (https://imgur.com/a/VqOtD) it pops out before being immediate sent back off the page. Maybe it's because the physics in my chart are still active? I tried setting:     
```
events: {
      callbacks: {
        animation: {
          freezePage: true
```

**Comment by dcdeiv** [comment]
jQuery-UI is indeed optional. However you used an example that used it.
Please, read carefully the options!

**Comment by dcdeiv** [comment]
I closed this issue since it's not a bug.
If you want to be helped you should provide the is and html snippets.

**Comment by laynetrain** [comment]
The issue was that my js was loading twice so it was opening and then immediately closing the open. It was due to the way I was extending my js in my templates.
